

public class UNOColorChooser extends javax.swing.JDialog {

    private int colorChosen;
    
    /** Creates new form UNOColorChooser */
    public UNOColorChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        colorChosen = 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonsPane = new javax.swing.JPanel();
        redButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        labelPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        
        setTitle("Choose the new color");
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("colorChooser");
        setModal(true);
        setResizable(true);
        
        redButton.setMnemonic('R');
        redButton.setForeground(java.awt.Color.white);
        redButton.setText("Red");
        redButton.setBackground(new java.awt.Color(204, 0, 0));
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });
        
        buttonsPane.add(redButton);
        
        greenButton.setMnemonic('G');
        greenButton.setForeground(java.awt.Color.white);
        greenButton.setText("Green");
        greenButton.setBackground(new java.awt.Color(0, 102, 0));
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });
        
        buttonsPane.add(greenButton);
        
        blueButton.setMnemonic('B');
        blueButton.setForeground(java.awt.Color.white);
        blueButton.setText("Blue");
        blueButton.setBackground(new java.awt.Color(0, 0, 204));
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });
        
        buttonsPane.add(blueButton);
        
        yellowButton.setMnemonic('Y');
        yellowButton.setForeground(java.awt.Color.white);
        yellowButton.setText("Yellow");
        yellowButton.setBackground(new java.awt.Color(255, 204, 0));
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });
        
        buttonsPane.add(yellowButton);
        
        getContentPane().add(buttonsPane, java.awt.BorderLayout.CENTER);
        
        labelPane.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel1.setText("Choose a new color:");
        labelPane.add(jLabel1);
        
        getContentPane().add(labelPane, java.awt.BorderLayout.NORTH);
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screenSize.width-getWidth())/2,(screenSize.height-getHeight())/2);
    }//GEN-END:initComponents
	
	public int getColor() {
		this.setVisible(true);
		
		return colorChosen;
	}
	
    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        colorChosen = Card.BLUE;
        closeDialog();
    }//GEN-LAST:event_blueButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        colorChosen = Card.YELLOW;
        closeDialog();
    }//GEN-LAST:event_yellowButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        colorChosen = Card.GREEN;
        closeDialog();
    }//GEN-LAST:event_greenButtonActionPerformed

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        colorChosen = Card.RED;
        closeDialog();
    }//GEN-LAST:event_redButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog() {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPane;
    private javax.swing.JButton redButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JButton blueButton;
    private javax.swing.JButton yellowButton;
    private javax.swing.JPanel labelPane;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
