
import javax.swing.Icon;

public class UNOAboutDialog extends javax.swing.JDialog {

    /** Creates new form UNOAboutDialog */
    public UNOAboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        titleLabel = new javax.swing.JLabel();
        infoScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        niceButton = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        titleLabel.setFont(new java.awt.Font("Dialog", 1, 24));
        titleLabel.setForeground(new java.awt.Color(102, 102, 152));
        titleLabel.setIcon((Icon) java.awt.Toolkit.getDefaultToolkit().createImage("C:\\Users\\Ryan\\Desktop\\Spring 2015\\401\\Uno\\resources\\unoicon.png"));
        titleLabel.setText("UNO");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(3, 11, 3, 11);
        getContentPane().add(titleLabel, gridBagConstraints1);
        
        infoScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        infoTextArea.setEditable(false);
        infoTextArea.setLineWrap(true);
        infoTextArea.setText("");
        infoScrollPane.setViewportView(infoTextArea);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(infoScrollPane, gridBagConstraints1);
        
        niceButton.setText("Nice");
        niceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niceButtonActionPerformed(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.insets = new java.awt.Insets(4, 0, 4, 0);
        getContentPane().add(niceButton, gridBagConstraints1);
        
        pack();
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screenSize.width-this.getWidth())/2,(screenSize.height-this.getHeight())/2);
        setTitle("About UNO");
    }//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void niceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niceButtonActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_niceButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleLabel;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JButton niceButton;
    // End of variables declaration//GEN-END:variables
}
