

import javax.swing.JFrame;
import javax.swing.event.*;
import java.io.*;
import java.net.URL;

public class UNOHelpScreen extends javax.swing.JFrame{

    /** Creates new form UNOHelpScreen */
    public UNOHelpScreen(JFrame parent, String file) {
        initComponents();
        
        this.parent = parent;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        okPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        helpScrollPane = new javax.swing.JScrollPane();
        helpHtmlPane = new javax.swing.JEditorPane();
        
        setTitle("UNO Help Screen");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        okPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        jLabel1.setText("UNO for Java Help Screen");
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        okPanel.add(jLabel1);
        
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        okPanel.add(jButton1);
        
        getContentPane().add(okPanel, java.awt.BorderLayout.SOUTH);
        
        helpScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        helpScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        helpScrollPane.setPreferredSize(new java.awt.Dimension(610, 24));
        helpScrollPane.setViewportView(helpHtmlPane);
        
        getContentPane().add(helpScrollPane, java.awt.BorderLayout.CENTER);
        
        pack();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage("C:\\Users\\Ryan\\Desktop\\Spring 2015\\401\\Uno\\resources\\unoicon.png"));
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(610, 450));
        setLocation((screenSize.width-610)/2,(screenSize.height-450)/2);
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dispose();
        parent.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
        dispose();
        parent.repaint();
    }//GEN-LAST:event_exitForm

	 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel okPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane helpScrollPane;
    private javax.swing.JEditorPane helpHtmlPane;
    private javax.swing.JFrame parent;
    // End of variables declaration//GEN-END:variables

}
