

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class UNOWindow extends JFrame {

	public static void main(String[] args) {
		new UNOWindow().setVisible(true);
	}

    /** Creates new form UNOWindow */
    public UNOWindow() {
    	options = new Options();
        game = new UNOGame(options);

        initComponents();
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        menuBar           = new JMenuBar();
        fileMenu          = new JMenu();
        newGameMenuItem   = new JMenuItem();
        optionsMenuItem   = new JMenuItem();
        separator1        = new JSeparator();
        exitUnoMenuItem   = new JMenuItem();
        helpMenu          = new JMenu();
        helpUnoMenuItem   = new JMenuItem();
        helpMenuSeparator = new JSeparator();
        aboutUnoMenuItem  = new JMenuItem();
        optionsDialog     = new OptionsDialog(this, true, options);
        
        fileMenu.setText("File");
		fileMenu.setMnemonic('F');
        newGameMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.ALT_MASK));
        newGameMenuItem.setText("New game");
        newGameMenuItem.setMnemonic('N');
        newGameMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to start a new game?", "New Game?",  JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION)
                {
                    newGameMenuItemActionPerformed(evt);
                    UNOPanel.played.clear();
                }
                
            }
        });
        
        fileMenu.add(newGameMenuItem);
        optionsMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.ALT_MASK));
        optionsMenuItem.setText("Options...");
        optionsMenuItem.setMnemonic('O');
        optionsMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                optionsMenuItemActionPerformed(evt);
            }
        });
        
        fileMenu.add(optionsMenuItem);
        fileMenu.add(separator1);
        exitUnoMenuItem.setText("Exit UNO");
        exitUnoMenuItem.setMnemonic('X');
        exitUnoMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Exit Game?",  JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION)
                {
                    exitUnoMenuItemActionPerformed(evt);
                }
            }
        });
        
        fileMenu.add(exitUnoMenuItem);
        menuBar.add(fileMenu);
        
        helpMenu.setText("Help");
        fileMenu.setMnemonic('H');
        helpUnoMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0));
        helpUnoMenuItem.setText("Help...");
        helpUnoMenuItem.setMnemonic('H');
        helpUnoMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                helpUnoMenuItemActionPerformed(evt);
            }
        });
        
        helpMenu.add(helpUnoMenuItem);
        helpMenu.add(helpMenuSeparator);
        aboutUnoMenuItem.setText("About UNO...");
        aboutUnoMenuItem.setMnemonic('A');
        aboutUnoMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                aboutUnoMenuItemActionPerformed(evt);
           }
        });
        
        helpMenu.add(aboutUnoMenuItem);
        menuBar.add(helpMenu);
        
        setTitle("UNO for Java");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("unoFrameWindow");
        //setIconImage(getIconImage());
        setResizable(true);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        setJMenuBar(menuBar);
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(610, 450));
        setLocation((screenSize.width-610)/2,(screenSize.height-450)/2);
        
        setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getClassLoader().getResource("\\resources\\unoicon.png")));
        
        gamePane = new UNOPanel(this, game, options);
        getContentPane().add(gamePane, java.awt.BorderLayout.CENTER);
    }//GEN-END:initComponents

    private void helpUnoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpUnoMenuItemActionPerformed
        helpScreen.show();
    }//GEN-LAST:event_helpUnoMenuItemActionPerformed

    private void optionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsMenuItemActionPerformed
        optionsDialog.show();
        gamePane.repaint();
        gamePane.repaint();
    }//GEN-LAST:event_optionsMenuItemActionPerformed

    private void aboutUnoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUnoMenuItemActionPerformed
        new UNOAboutDialog(new javax.swing.JFrame(), true).show();
        gamePane.repaint();
    }//GEN-LAST:event_aboutUnoMenuItemActionPerformed

    private void exitUnoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitUnoMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitUnoMenuItemActionPerformed

    private void newGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameMenuItemActionPerformed
		options = optionsDialog.getOptions();
        gamePane.newGame(options);
    }//GEN-LAST:event_newGameMenuItemActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JMenuItem optionsMenuItem;
    private javax.swing.JSeparator separator1;
    private javax.swing.JMenuItem exitUnoMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpUnoMenuItem;
    private javax.swing.JSeparator helpMenuSeparator;
    private javax.swing.JMenuItem aboutUnoMenuItem;
    private UNOPanel gamePane;
    // End of variables declaration//GEN-END:variables
    
    private UNOHelpScreen helpScreen = new UNOHelpScreen(this, "/resources/UNOHelp.htm");
    private static UNOGame game;
    private OptionsDialog optionsDialog;
    private static Options options;
}
